import {
  Smartphone,
  Tablet,
  Headphones,
  Watch,
  PackageSearch,
  Laptop,
  Shirt,
  ShoppingBag,
  Gem,
  Car,
  Bike,
  Utensils,
  Home,
  ShoppingCart,
  Droplets,
  Trophy,
  Glasses,
  Sparkles,
  Flame,
  Sofa,
} from 'lucide-react'
import { getCategoryCollectionPath } from './categoryRoutes'

const iconMap = {
  smartphones: Smartphone,
  tablets: Tablet,
  headphones: Headphones,
  'womens-watches': Watch,
  'mens-watches': Watch,
  laptops: Laptop,
  'mobile-accessories': Smartphone,
  fragrances: Sparkles,
  skincare: Droplets,
  'skin-care': Droplets,
  groceries: ShoppingCart,
  'home-decoration': Home,
  furniture: Sofa,
  tops: Shirt,
  'womens-dresses': Shirt,
  'womens-shoes': PackageSearch,
  'mens-shirts': Shirt,
  'mens-shoes': PackageSearch,
  'womens-bags': ShoppingBag,
  'womens-jewellery': Gem,
  sunglasses: Glasses,
  automotive: Car,
  motorcycle: Bike,
  lighting: Flame,
  beauty: Sparkles,
  'kitchen-accessories': Utensils,
  'sports-accessories': Trophy,
  vehicle: Car,
}

const labelMap = {
  smartphones: 'Điện thoại',
  tablets: 'Máy tính bảng',
  headphones: 'Tai nghe',
  'womens-watches': 'Đồng hồ nữ',
  'mens-watches': 'Đồng hồ nam',
  laptops: 'Laptop',
  'mobile-accessories': 'Phụ kiện điện thoại',
  fragrances: 'Nước hoa',
  skincare: 'Chăm sóc da',
  'skin-care': 'Chăm sóc da',
  groceries: 'Đồ ăn',
  'home-decoration': 'Trang trí nhà',
  furniture: 'Đồ nội thất',
  tops: 'Áo',
  'womens-dresses': 'Váy nữ',
  'womens-shoes': 'Giày nữ',
  'mens-shirts': 'Áo nam',
  'mens-shoes': 'Giày nam',
  'womens-bags': 'Túi xách nữ',
  'womens-jewellery': 'Trang sức nữ',
  sunglasses: 'Kính mát',
  automotive: 'Ô tô',
  motorcycle: 'Xe máy',
  lighting: 'Đèn',
  beauty: 'Mỹ phẩm',
  'kitchen-accessories': 'Phụ kiện bếp',
  'sports-accessories': 'Phụ kiện thể thao',
  vehicle: 'Xe cộ',
}

export function mapApiCategoriesToCategoryItems(apiCategories) {
  return apiCategories.map((category) => {
    const categoryKey = category.slug || category
    const categoryName = category.name || category

    return {
      key: categoryKey,
      sidebarLabel: labelMap[categoryKey] || categoryName,
      stripLabel: labelMap[categoryKey] || categoryName,
      icon: iconMap[categoryKey] || PackageSearch,
      href: getCategoryCollectionPath(categoryKey),
      tone: ['#6c7dff', '#ff6ea8'],
      showInStrip: true,
    }
  })
}
